version: "3.2"

services:
  python:       
    build: 
      dockerfile: ./docker/Dockerfile
      context: ./
    image: my_project_python
    env_file:
      - ./docker/.env
    ports:
      - "8888:8888"
    command: 
      jupyter lab --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    volumes:
      - ./data:/data
      - ./code:/code
      - ./notebooks:/notebooks

