name: base                                                                   
channels:                                                                    
  - defaults                                                                 
dependencies:                                                                
  - pandas=0.22.0
  - jupyterlab